SELECT E.ID,E.NAME, COUNT(S.ID) AS SALES_C, 
RANK() OVER (ORDER BY COUNT(S.ID) DESC) AS SALES_RANK_C, 
SUM(S.PRICE) AS SALES_S, 
RANK() OVER (ORDER BY SUM(S.PRICE) DESC) AS SALES_RANK_S
FROM  SALES S
RIGHT JOIN EMPLOYEE E ON S.EMPLOYEE_ID = E.ID
GROUP BY E.ID
ORDER BY SALES_C DESC, SALES_RANK_C, SALES_S DESC, SALES_RANK_S;