WITH RECURSIVE DATES AS (
  SELECT CURRENT_DATE::TIMESTAMP AS DATE, 0 AS I
  UNION
  SELECT DATE + (2+RANDOM()*5) * '1 DAY'::INTERVAL, I +1
  FROM DATES
  WHERE I < 99
)
SELECT TO_CHAR(DATE, 'DD.MM.YYYY') AS ДАТЫ_ПРОВЕРОК
FROM DATES
ORDER BY DATE;